### ISSUE TITLE
TCN

### ISSUE THREAD

**Issue by weiran96** [Songweiping/TCN-TF#1]
Do you use the  weight normalization in your code？

**Comment by Songweiping** [comment]
Hi @weiran96 ,

WN is ignored in my implementation, because I did not find any proper API in TensorFlow. The wrapper of WN is still an active feature request in TF (see https://github.com/tensorflow/tensorflow/issues/10125). Do you have any idea incorporating WN in 1d convolution quickly? 

Weiping

**Comment by weiran96** [comment]
Is there any influence on results without WN?

**Comment by Songweiping** [comment]
I feel it may improve the performance more or less significantly.

**Comment by YuanTingHsieh** [comment]
Hi @weiran96 @Songweiping ,
I've implemented a version with WN in [here](https://github.com/YuanTingHsieh/TF_TCN)
Specifically in this [file](https://github.com/YuanTingHsieh/TF_TCN/blob/master/tcn/tcn.py)

Actually, I've tested the adding problem with and without WN in the original torch code,
And without WN, it can't converge to a good result

**Comment by Songweiping** [comment]
@YuanTingHsieh Thanks for sharing your code and experience with WN.

The WN is included in this repo now, along with a general 1d convolution operator. However, I am still expecting an elegant way to integrate WN for TF layers, something like WeightNorm(conv_layer).
