### ISSUE TITLE
1D Weight Normalization Issue

### ISSUE THREAD

**Issue by Supermaxman** [Songweiping/TCN-TF#2]
I think you may be performing weight normalization incorrectly for 1D convolutions. 

In wnconv1d.py on line 58 you perform the following:

`self.kernel = tf.reshape(g,[1,1,num_filters]) * nn_impl.l2_normalize(kernel, [0, 1, 2]) `

This l2 normalization normalizes over axes [0, 1, 2]. I believe this is incorrect for 1D convolutional weight normalization as you are performing l2 normalization over the filter dimension. 

These axes would be correct if you were performing 2D convolution, since you would be performing l2 normalization over the two spacial and one input channel dimensions, but since you have only a single spacial dimension in 1D convolutions I think you may want to change your normalization axes to [0, 1]. 

If you want to maintain a rank-independent _WNConv layer you may want to generate those axes based on the provided rank or shape of kernel. Please let me know if I missed something here.

**Comment by Songweiping** [comment]
Yes, normalization axes should not include [2] in 1D convolution case. Thanks for your suggestions!
