### ISSUE TITLE
convolutional_layers._Conv

### ISSUE THREAD

**Issue by Levstyle** [Songweiping/TCN-TF#3]
cant find _Conv in convolutional_layers

**Comment by zhangjie93** [comment]
I thin the problem is tensorflow version. I find _Conv in tensorflow-gpu 1.5

**Comment by zhangjie93** [comment]
I think the problem is tensorflow version. I find _Conv in tensorflow-gpu 1.5

**Comment by Levstyle** [comment]
> I think the problem is tensorflow version. I find _Conv in tensorflow-gpu 1.5

You're right! Do u know how to fix this code to make it compatible with the newest TF

**Comment by iliegg** [comment]
I replace the _Conv with this class "with tensorflow.python.keras.layers.convolutional import Conv", and then delete two parameters "_reuse", "_scope" at the sentence initiating the class "WNConv1D" in the fucntion "wnconv1d". 
It seems feasible on my computer with tensorflow 1.10.0. I think you can also try it.

**Comment by Songweiping** [comment]
It seem to be solved. Close now:)
